### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes https://github.com/oceanhackweek/ohw-tutorials/issues/37

### CODE REVIEW

**Comment by cathmmitchell** [comment]
This all looks good to me

**Comment by ocefpaf** [comment]
@kathy

> This all looks good to me
let me get the tests to pass and clean this up a bit more. I'll merge it ASAP.

**Comment by ocefpaf** [comment]
Pending on https://github.com/conda-forge/dask-gateway-feedstock/pull/20

**Comment by ocefpaf** [comment]
Merging this to avoid a "monster" PR and so people can start submitting the notebooks. More changes in a few...

**Pull request merged**
