### PR TITLE
Ohw22 machine learning

### PR DESCRIPTION
**Pull request by valentina-s**
This PR contains materials for Tuesday afternoon ML session. It is still under dev.

### CODE REVIEW

**Comment by valentina-s** [comment]
@ocefpaf I will merge this, I believe it affects only my files.

**Comment by ocefpaf** [comment]
> @ocefpaf I will merge this, I believe it affects only my files.

Go for it! Thanks!!

**Comment by valentina-s** [comment]
Nevermind, I do not have the rights. @ocefpaf  Could you do it?

**Comment by ocefpaf** [comment]
> Nevermind, I do not have the rights. @ocefpaf Could you do it?

Fixed that too. Let me know if you got the invite.

**Pull request merged**
