### PR TITLE
Adding changes for Data Access in R Tutorial

### PR DESCRIPTION
**Pull request by jevanilla**

### CODE REVIEW

**Comment by jevanilla** [comment]
The commit I'd like to bring in is actually 275ae77. 144608a has corrupted files.

**Comment by b-reyes** [comment]
Hello @jevanilla I rolled back your PR to the branch you requested.

**Comment by leewujung** [comment]
@jevanilla : could you resolve the conflicts that have arisen?  after @b-reyes has rolled back the commit you requested.

**Comment by jevanilla** [comment]
@leewujung Should be good to go now

**Pull request merged**
