### PR TITLE
add link to slides for reproducible research

### PR DESCRIPTION
**Pull request by eeholmes**

### CODE REVIEW

**Comment by eeholmes** [comment]
@valentina-s

**Comment by valentina-s** [comment]
Thanks @eeholmes! Since your focus is more on collaboration rather than reproducing some research, you can reflect this in the title. Also could you coordinate with @dgumustel (I believe she is teaching Git) regarding some of the git topics/their order of introduction, and the assumption of what we expect people to know in advance. I like the idea of explaining the value of github for collaboration before diving into some technical git details.

**Comment by eeholmes** [comment]
@valentina-s Ok I will check with @dgumustel. I can give a different tutorial focused more on reproducibility and less on collaboration.

**Comment by valentina-s** [comment]
@eeholmes Collaboration is good since it sets the right tone in the beginning! You can update your title and description accordingly.

**Pull request merged**
