### PR TITLE
OHW 2023 Reproducible Science

### PR DESCRIPTION
**Pull request by asx-**
Testing the drag and add functionality on github for this

### CODE REVIEW

**Comment by asx-** [comment]
Tagging @emiliom as a check that the github file upload ability worked correctly since I didn't upload from a CLI this time

**Comment by ocefpaf** [comment]
Do you have that online, like google docs, so folks can view it without download it?

**Comment by emiliom** [comment]
Or upload it as a pdf instead, or in addition to the powerpoint.

**Comment by asx-** [comment]
Added pdf. Should we add a OHW23 specific Google Drive subdir for tutorials? Otherwise I'll add it to my personal Drive with read only permissions

**Comment by emiliom** [comment]
I wasn't finding the files you added, until I realized this PR was done against `main`, not `OHW23`. I need to focus on something else right now, but I can get to it later in the day unless someone else can take care of it earlier.

**Comment by ocefpaf** [comment]
> I wasn't finding the files you added, until I realized this PR was done against `main`, not `OHW23`. I need to focus on something else right now, but I can get to it later in the day unless someone else can take care of it earlier.

Blerg. My bad actually. Let's revert this one and redirect.

**Comment by ocefpaf** [comment]
It seems I cannot re-open it. I'll re-issue this one in a moment.

**Comment by asx-** [comment]
Whoops. At least it wasn't so bad to fix, but teaches me something new while trying new to me functionality.

**Pull request merged**
