### PR TITLE
Notebook for data access Python tutorial

### PR DESCRIPTION
**Pull request by mhidas**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Great tutorial! I can try to help with some of the items in your list at the end:


- Find alternative data sources in other regions (at least US)

It would be great if you could mentioned IOOS too, even better if you can make a parallel on IMOS and IOOS and the shared tech between them. There are tons of examples in https://ioos.github.io/ioos_code_lab/content/intro.html but I would choose something quick, to avoid cluttering the tutorial, and that introduces another data source ERDDAP. Maybe an update version of https://ioos.github.io/ioos_code_lab/content/code_gallery/data_access_notebooks/2016-10-12-fetching_data.html?highlight=erddap where we show the hotub water temperatures Florida is experiencing this summer?
 
- Provide sample data to store on JupyterHub for local access

I really like the pooch approach for this. Where we publish the [data as an asset](https://github.com/LaPoGeoMar/Proj_Modelagem_Oleo/releases/tag/v0.1.0) on GH and fetch them with pooch ([first cell of this notebook](https://github.com/LaPoGeoMar/Proj_Modelagem_Oleo/blob/v0.1.0/02-aggregate-seasons.ipynb)). This will enable a poor's man version control for the data, local download/cache, and would free our servers from hosting large files. Note that GH assets are limited to 2G files but it OK for most demos.

- Acknowledge previous tutorial and other sources...

If you are using any of my sources, no need. It is all under "OHW23" anyway.
 
You also mentioned the use of a parquet dataset. I know a few for bio-oceanography looking into them and I can post it here if you want to give them a look.

**Comment by mhidas** [comment]
Thanks for the helpful comments @ocefpaf . I agree adding some IOOS examples would be helpful. 

I don't think I will talk about ERDDAP in my tutorial as it is not a service I am familiar with and the content I have so far is almost enough to fill the 45min time available (allowing time for people to run the notebook and some questions). 

I was thinking of just listing some additional access methods at the end of the notebook, with links to other tutorials.

**Comment by mhidas** [comment]
Ok, this is more or less ready to go now!

**Comment by mhidas** [comment]
I'm assuming the local copies of the datasets I provide will be located in an `IMOS` folder under the `shared` folder I can see on the JupyterHub.

**Review by abkfenris — COMMENTED** [review]
Looking pretty nice!

When I tried to switch to the shared cache, the paths didn't work exactly right. I think it's from NFS mount weirdness, so using an absolute path to shared `/home/jovyan/shared` may make things more predictable.

The opendap URL is generated in a code block that folks may entirely skip or comment out if they are using the local data, which could cause following cells to fail.

Double `#` on comments in blocks with commented out code will make it less likely that folks try to quickly strip the comments on the block and then get really weird failures.

It hung while trying to make a geoviews plot from Zarr, but I was able to continue querying the Zarr and Parquet datasets afterwards.

**Comment by ocefpaf** [comment]
@abkfenris I believe we can probably turn off Review Notebook App here. GH has a nice notebook diff now and using the app requires a few more clicks to see the diffs.

**Comment by mhidas** [comment]
Thanks @abkfenris . I've updated those bits.

I also just ran the notebook on the JupyterHub and that led to a couple of additional changes. 

Unfortunately I also didn't get the map plot from the Zarr files (I think the problem is the chunking is too small - so dask has a lot of tasks to contend with...)

**Comment by abkfenris** [comment]
Ah, that can be a problem especially with holo/geoviews as it does a lot of work behind the scenes. What if you pull the zds sst slicing out into a separate cell, and explicitly load that?

**Pull request merged**
