### PR TITLE
Adding reproducible science slides

### PR DESCRIPTION
**Pull request by MathewBiddle**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@MathewBiddle the pptx is 52.3 MB while the pdf is ~7MB. Do you need both or can we keep only the latter?

**Comment by MathewBiddle** [comment]
blerg. I stuck a .gif animation in the ppt. Just keep the pdf and I'll present from the ppt locally. I'll make the change

**Comment by ocefpaf** [comment]
> blerg. I stuck a .gif animation in the ppt. Just keep the pdf and I'll present from the ppt locally. I'll make the change

If you need the animation it is fine. We can afford 53 MB. I thought both files were redundant.

**Comment by MathewBiddle** [comment]
they are'ish. no big deal.

**Pull request merged**
