### PR TITLE
Add tutorial spacial tidy data with R

### PR DESCRIPTION
**Pull request by paocorrales**
I wasn't able to push to the repository so, here is a PR.

### CODE REVIEW

**Review by ocefpaf — APPROVED** [review]
Looks great! Thatnks!

I'll leave merging to @emiliom so we can have a set set of eyes.

**Comment by emiliom** [comment]
It looks great, thanks!! As I mentioned over email, it looks like we don't yet have a couple of the libraries in our R image. But we'll manage. For reference, the libraries seem to be:

- `emo`
- `markdown` (though we do have `rmarkdown`)
- `metR`
- `udunits2`
- `xaringan`

Gracias!

**Comment by ocefpaf** [comment]
I can work on adding emo to conda-forge next Monday. If it is on CRAN it should be easy, then we can send a single PR adding those to the hub image.

**Comment by abkfenris** [comment]
> @emiliom @paocorrales Looks like `emo` is not available. https://github.com/oceanhackweek/jupyter-image/runs/7822558056?check_suite_focus=true#step:6:2632

_Originally posted by @abkfenris in https://github.com/oceanhackweek/jupyter-image/issues/55#issuecomment-1214247126_

**Comment by abkfenris** [comment]
These dependencies will be available after https://github.com/2i2c-org/infrastructure/pull/1624 is merged

**Pull request merged**
