### PR TITLE
sfnetworks: Analisis de redes espaciales en R

### PR DESCRIPTION
**Pull request by loreabad6**
Hi, 

I was on the last details of my R-spatial tutorial in spanish when I noticed that https://github.com/oceanhackweek/ohw-tutorials/pull/91 and possibly (I am not sure if this is the one in spanish too) https://github.com/oceanhackweek/ohw-tutorials/pull/89/ might have too much overlap to what I was aiming to show. I would say that for the attendees, this would be repetitive and not useful. 

Alternatively, I can talk about spatial network analysis in R with sfnetworks. For that I would need `sfnetworks`, `tidygraph`, `igraph` on the JupyterHub. Let me know what you prefer, I am fine with either option. I added folders for both but of course we can keep only the final tutorial you want me to give 😄 

Ping @emiliom and @lidefi87

### CODE REVIEW

**Comment by abkfenris** [comment]
Have you checked if those packages are already on the hub? If they aren't please make a comment on https://github.com/oceanhackweek/jupyter-image/issues/49 so that whomever does the next round of updates to the image can take care of them.

**Comment by emiliom** [comment]
Hi @loreabad6 . We realized just recently this overlap between your original tutorial and the one given yesterday (https://github.com/oceanhackweek/ohw-tutorials/tree/OHW22/optional/espanol/datos-espaciales-tidy). As @lidefi87 is an R user (I'm not) and she's more familiar with your work, I defer to her for a decision on how to proceed. Right now it's late night in Australia, so we'll have to wait several hours to see what she thinks.

Thanks for submitting the request for the extra packages per @abkfenris's instructions. I think we'll hold off a bit while we wait for @lidefi87 and also while we address a potentially important R package problem we ran into this morning.

**Comment by lidefi87** [comment]
Hello everyone! I am just going through messages here, so apologies for the delay in getting back to you. @loreabad6, the other tutorial in Spanish had a lot more spatial analysis content than I expected, so I think it would be better if we could switch to sfnetwork. I hope this is not too much trouble for you.

**Comment by loreabad6** [comment]
Hi @lidefi87 and @emiliom, sounds good then I will focus on sfnetworks today. @abkfenris @emiliom let me know if I can help in any way with package install. Alternatively, in case of emergency, I can launch a binder with my tutorial and share the link with attendees 😉

**Comment by lidefi87** [comment]
Sounds great! 😊 thanks so much @loreabad6 for being so flexible

**Comment by loreabad6** [comment]
Thank you all, from my side the tutorial is ready. I think the packages are not yet on the JupyterHub, but for now I also have the demo here: https://mybinder.org/v2/gh/sfnetworks/rladies-gye/main?urlpath=rstudio

**Comment by emiliom** [comment]
According to https://github.com/oceanhackweek/jupyter-image/issues/49#issuecomment-1218173360, the packages may be available in time for the tutorial!
Gracias @loreabad6 !

I will go ahead and merge this PR. If you need to make changes, you can just submit a new PR

**Comment by emiliom** [comment]
@loreabad6 I forgot to say that having your binder as a plan B is great. Thank you

**Pull request merged**
